ALTER TABLE documents ADD COLUMN IF NOT EXISTS video_url TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS video_filename VARCHAR(255);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS video_size_bytes BIGINT DEFAULT 0;
